version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <ECR_URL>
  build:
    commands:
      - docker build -t <IMAGE_NAME>.
      - docker tag <IMAGE_NAME> <ECR_URL>
  post_build:
    commands:
      - docker push <ECR_URL>
      - printf '[{"name":"helloWorld","imageUri":"%s"}]' <ECR_URL> > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
