version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 737327749629.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t express-app:latest .
      - docker tag express-app:latest 737327749629.dkr.ecr.us-east-1.amazonaws.com/express-app:latest
  post_build:
    commands:
      - docker push 737327749629.dkr.ecr.us-east-1.amazonaws.com/express-app:latest
      - printf '[{"name":"helloWorld","imageUri":"%s"}]' 737327749629.dkr.ecr.us-east-1.amazonaws.com/express-app:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
